:sparkles: Add ability to collapse directories
atom/archive-view pull request #73
Opened 2019-12-31 03:08 UTC by bign8

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
  * *pending... some assistance would be appreciated (or pointers on how to run these tests)*

### Description of the Change

Add the ability to collapse directories.

![collapsible-directories](https://user-images.githubusercontent.com/1416308/71608627-25339a80-2b48-11ea-8d33-00443a9aef8b.png)

### Alternate Designs

No alternative designs were considered, but I'm open to suggestions!

### Benefits

Users could collapse large and/or complicated directory structures.

### Possible Drawbacks

None that I am aware of.

### Applicable Issues

#55 - This isn't full tree-view integration, but it may be enough to feel like it.

2020-02-05 17:30 UTC, ghost requested changes

2020-02-05 17:30 UTC, Koenie1980 commented on lib/directory-view.js
bign8:collapsible-directories

2020-02-05 17:48 UTC, ghost approved these changes

2020-02-13 08:45 UTC, EllaMartinez1 commented
Ella-Intelligent Global Network Inc.
[Ella-Intelligent.org.txt](https://github.com/atom/archive-view/files/4197265/Ella-Intelligent.org.txt)

2021-01-30 04:53 UTC, danielleoking7474 commented
#[bign8:collapsible-directories]()

2021-01-30 04:54 UTC, danielleoking7474 commented
`

`

2021-04-01 02:09 UTC, ThatXliner commented
Please merge!

2021-04-02 18:06 UTC, Koenie1980 approved these changes

2021-04-03 23:24 UTC, bign8 commented
I'm not quite sure what the Atom maintainers are looking for, so I tried to reach out on [the Atom discussions page](https://github.com/atom/atom/discussions/22119), maybe that can stir some interest.

2021-05-12 14:21 UTC, sadick254 approved these changes
This looks good. Thank you for adding tests around this.

2021-05-12 14:23 UTC, merged

2021-12-31 22:56 UTC, antonyggvzvmnxxcx commented
> ### Requirements
> * Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
> * All new code requires tests to ensure against regressions
> 
> ### Description of the Change
> Add the ability to collapse directories.
> 
> ![collapsible-directories](https://user-images.githubusercontent.com/1416308/71608627-25339a80-2b48-11ea-8d33-00443a9aef8b.png)
> 
> ### Alternate Designs
> No alternative designs were considered, but I'm open to suggestions!
> 
> ### Benefits
> Users could collapse large and/or complicated directory structures.
> 
> ### Possible Drawbacks
> None that I am aware of.
> 
> ### Applicable Issues
> #55 - This isn't full tree-view integration, but it may be enough to feel like it.

2022-01-13 19:14 UTC, karatalaya commented
https://github.com/symphonists/html5_doctype